### PR TITLE
useStarknetDeploy hook

### PR DESCRIPTION
**Pull request by clementjuventin**
Add a `useStarknetDeploy` hook for deploying a contract.

### CODE REVIEW

**Comment by fracek** [comment]
Looks good!

A couple of small things:

* can you generate a changeset with `pnpm changeset`?
* would be amazing if we had a section in `<Demo />` with a button that deploys a new contract.

**Comment by clementjuventin** [comment]
@fracek  -  No problem. However I have trouble accessing the demo page, either it loads indefinitely or it doesn't work. I tested both from your repository and locally on my machine and it doesn't seem to work better. Can you try using the invoke button from the demo tab and tell me if it works for you?

**Comment by clementjuventin** [comment]
I added the changeset file and a dedicated section to deployment. I couldn't test it in the documentation project directly but I incorporated the sample in the following template `https://github.com/apibara/starknet-react/tree/main/examples/starknet-react-next` and it worked pretty well.

**Comment by fracek** [comment]
Perfect! I will merge this in the branch I'm making to refactor some code.

**Comment by fracek** [comment]
Merged in 9d81e3e9e3a0f37d8d8ddda210b47ed9b2575244. Thank you for your help!

**Pull request closed without merging**
