### PR TITLE
feat: add optional callback to handle tx status changing

### PR DESCRIPTION
**Pull request by J4ckyLIM**
Add optional callback functions to useTransaction and useTransactions hook that will handle each status of the transaction.

### CODE REVIEW

**Comment by fracek** [comment]
Looks good, but I believe the callbacks should be called inside the `onSuccess` callback for `useQuery`.

**Comment by J4ckyLIM** [comment]
> 

Yep you're right, it would make more sense !

**Comment by J4ckyLIM** [comment]
This can be reviewed I think :)

**Comment by fracek** [comment]
Hey, I added the `useTransactionReceipt` hook in #180. I think you should add the callbacks to that hook and not `useTransaction`.

**Comment by J4ckyLIM** [comment]
You're right, it makes more sense, i'll do to it ASAP :) (likely in 10 hours or so)

**Comment by J4ckyLIM** [comment]
Closing this PR, work done [here](https://github.com/apibara/starknet-react/pull/188)

**Pull request closed without merging**
