### PR TITLE
Upgrade skartnetkit to latest version

### PR DESCRIPTION
**Pull request by lindsaymoralesb**
# Issue
Solves #483 

# Solution
- Starknetkit was updated to its latests version `2.2.25` using `pnpm add starknetkit@next`.
- The app commands were tested to make this wasn't a breaking change (`build`, `preview`, `dev`, ...)
- The [release docs](https://github.com/argentlabs/starknetkit/releases) as well as the specific [code](https://github.com/argentlabs/starknetkit/commit/071acfb1c62ccc241f5723835db387ff2ab64488) were checked to make sure there was no breaking change or code needed to be change on the demo project.
- A complete test was performed while running the demo locally. Both argent and braavos wallet's connection was tested.

### CODE REVIEW

**Comment by lindsaymoralesb** [comment]
Hi @fracek just noticed that today's morning the released another update for starknetkit (`2.2.26`) let me know if I should update it again.

**Comment by fracek** [comment]
Hey, yes if you can update to the latest release.

**Comment by lindsaymoralesb** [comment]
@fracek I read the latest [release docs](https://github.com/argentlabs/starknetkit/releases) for `v2.2.26` and tested the demo again. There are no breaking changes that cause a change in code.
Ready for review!

**Comment by fracek** [comment]
Thank you for this!

**Pull request merged**
