### PR TITLE
feat: add starknetId hooks

### PR DESCRIPTION
**Pull request by 0xYami**
closes https://github.com/apibara/starknet-react/issues/202

Draft for `Starknet ID` hooks. Checking how to unit test them. My knowledge of both libraries is from few days ago but it looks like we need to generate an account whenever it's  used, I'm not sure it should be done this way

### CODE REVIEW

**Comment by fracek** [comment]
Thanks! I think you can use `call.test.tsx` as a starting point for writing tests for this.

**Comment by 0xYami** [comment]
Alright thanks, I will have a look. In the meantime, I opened another PR https://github.com/apibara/starknet-react/pull/205 to fix failing tests due to some changes on `starknet.js`. I will rebase this one after that.

**Comment by fracek** [comment]
I reviewed the other pr and it looks good.

Also I recommend running `pnpm changeset` when you're finished to document what changed (this one is a minor bump, which we use for breaking changes before 1.0).

**Comment by 0xBenaparte** [comment]
Hey @0xYami, 

I see that it's looking good tell me if you still need help for this PR !

**Comment by 0xYami** [comment]
Hi guys, apologies for the big delay, I'm currently in holidays with low access to Internet, I'll be able to continue this PR starting Tuesday. Feel free to update\re-open if it suits you. Sorry again for the delay 😬

**Comment by fracek** [comment]
No problems, enjoy the break!

**Comment by 0xBenaparte** [comment]
Hello @0xYami ! How is this PR doing ? Do you need any help 😉 ?

**Comment by 0xYami** [comment]
Hello there, I have a hard time running docker on my M1, feel free to take over

**Comment by fracek** [comment]
Done in #214

**Pull request closed without merging**
