### PR TITLE
174 receipt callback

### PR DESCRIPTION
**Pull request by J4ckyLIM**

### CODE REVIEW

**Comment by J4ckyLIM** [comment]
I don't see any comments :c

**Comment by fracek** [comment]
You should see the comments if you scroll in the files changed tab.

**Comment by J4ckyLIM** [comment]
Strange, there is no conversation in my side

**Comment by fracek** [comment]
Odd, let me paste here what I wrote: 

Line 174: I believe you should move this code that checks for the tx status in the [`onSuccess`](https://tanstack.com/query/v4/docs/reference/useQuery?from=reactQueryV3&original=https://react-query-v3.tanstack.com/reference/useQuery) callback provided by `useQuery`.

Line 225: No need to call the callbacks here. Restore to the original version of this function.

**Comment by fracek** [comment]
Looks good, last two small fixes:

1. remove return value from the `onSuccess` handlers.
2. remove call to callbacks in `refetchInterval`

**Comment by J4ckyLIM** [comment]
Done, sorry for the delay :x

**Comment by J4ckyLIM** [comment]
Any update sir ?

**Comment by fracek** [comment]
I will review it this weekend!

**Comment by fracek** [comment]
I squashed your changes to have a clean, linear history. The PR was merged in 315fd083493883fdf23a12d4ec02ea59f32277fc!

Thank you, and sorry for the long delay merging!

**Pull request closed without merging**
