### PR TITLE
feat: useConnector should return isLoading

### PR DESCRIPTION
**Pull request by 0xads**
#201 

- create isLoading boolean : initialize to true, on refresh when available is populated by connectors set isLoading to false
- update corresponding tests

### CODE REVIEW

**Comment by fracek** [comment]
Looks good. Can you address the comment I left, then run `pnpm changeset` to add a patch change.

**Comment by 0xads** [comment]
Hi, it's done.

**Comment by fracek** [comment]
Sorry, I'm used to graphite and forgot to submit the comment.

**Comment by 0xads** [comment]
Yes, my bad. The initial value should be false.
It's corrected and tests are updated.
Thanks for review.

**Comment by 0xads** [comment]
I made the change but i remembered my thoughts so I reset last commits.

The name "isLoading" is chosen to designate the connectors are in loading. 
Initially isLoading is true and after refresh the connectors are not longer in loading, so set to false.

In case you think it might be confusing and we switch the default value by true i think it's better to change the name maybe to areLoaded.

I'm open to talk about it :)

**Comment by fracek** [comment]
Interesting point. I thought `isLoading` was also about the initial load of connectors. The sequence of events in my mind is along the lines:

 * page is fetched (`isLoading = true`)
 * page is rendered (`isLoading = true`)
 * `useEffect` is called on first render, loads the connectors then returns. After this I would expect `isLoading = false`.
 * User action causes `refresh` to be called,  `isLoading = true`
 * Connectors are refreshed, `isLoading = false`

With the current behaviour, `isLoading = true` until `refresh` is called.

**Comment by 0xads** [comment]
I got it, was focus on "available" value.
Added isLoading on useEffect. I tried in a test application its works like in the sequence above.

**Comment by fracek** [comment]
Thank you for this!

**Pull request merged**
