### PR TITLE
feat: screen done

### PR DESCRIPTION
**Pull request by okhaimie-dev**
## Changes

- Welcome and Setup Screen ui made

### CODE REVIEW

**Comment by fracek** [comment]
Sorry for taking so long to review. I run the demo:

* can you use `tamagui` for the button and views? That way it's easy to set a consistent design.
* using `ToastAndroid` seems to break the web build. The web build is the most important one for now.
* Can you generate the private/public key in `setup.tsx`? We can use [jotai to persist the key across sessions](https://jotai.org/docs/guides/react-native)

**Comment by okhaimie-dev** [comment]
> Sorry for taking so long to review. I run the demo:
> 
> * can you use `tamagui` for the button and views? That way it's easy to set a consistent design.
> * using `ToastAndroid` seems to break the web build. The web build is the most important one for now.
> * Can you generate the private/public key in `setup.tsx`? We can use [jotai to persist the key across sessions](https://jotai.org/docs/guides/react-native)

Alright, I will take note of this and revert. Will make a PR in a bit

**Comment by okhaimie-dev** [comment]
> Can you generate the private/public key in setup.tsx? We can use [jotai to persist the key across sessions](https://jotai.org/docs/guides/react-native)

The web build fails when I try to use `starknet` as a dependency. 
Here is a branch where I am working to implement the account generation feature with jotai
https://github.com/okhaimie-dev/starknet-react/tree/jotai
And I am still trying to wrap my head around how to effectively get the account generation feature work in general.

Aside, I fixed the other issues.

**Comment by fracek** [comment]
Looks good! Thank you

**Pull request merged**
