### PR TITLE
feat(create-starknet): added command arguments support

### PR DESCRIPTION
**Pull request by YohanTz**
- Added `commander` and `chalk` as dependencies of `create-starknet`
- Added `--help` and `--version` options thanks to `commander`
- Made possible to create a project directly with the command `npx create-starknet [folder-name] and handled errors properly like below`
- Added some colors / formatting thanks to `chalk`

<div style="display: flex">
Screenshot 2023-03-02 at 01 06 38

Screenshot 2023-03-02 at 01 06 56
</div>

<div style="display: flex">
Screenshot 2023-03-02 at 01 08 58

Screenshot 2023-03-02 at 01 09 55
</div>

### CODE REVIEW

**Comment by fracek** [comment]
Can you add a changeset (`pnpm changeset`) to get credited in the release notes? Other than that, it's looks great!

**Comment by YohanTz** [comment]
> * Made possible to create a project directly with the command `npx create-starknet [folder-name] and handled errors properly like below`

Ok! I did it locally for now, should I add one or multiple changeset? It's my first time doing it

**Comment by fracek** [comment]
Multiple is better, but one is fine too. It's a way so that your work is credited properly.

**Comment by YohanTz** [comment]
Ok ! Updated 👍🏽

**Comment by fracek** [comment]
Perfect, thank you!

**Pull request merged**
